### ISSUE TITLE
Clean up warning when running the app

### ISSUE THREAD

**Issue by indraarianggi** [naufaldi/future-bright#2]
When start development server (npm run dev), I found some warnings popping up in the terminal:
- Attributes that should be written in camelCase ([here the reference](https://reactjs.org/docs/dom-elements.html#differences-in-attributes))
- Lack of `key` attributes on components that are rendered iteratively ([here the reference](https://reactjs.org/docs/lists-and-keys.html#keys))
- Misplacement of title and meta tags ([here the reference](https://nextjs.org/docs/messages/no-document-viewport-meta))

Can I work on this too?

<img width="1149" alt="Screen Shot 2022-10-19 at 09 30 22" src="https://user-images.githubusercontent.com/19724125/196584847-8d3ab597-e0c2-48d9-85bd-b8924978c9f1.png">

**Comment by naufaldi** [comment]
yes you can do it @indraarianggi

**Comment by indraarianggi** [comment]
cool
